<#
.SYNOPSIS
    Generate a comprehensive report in multiple formats.

.DESCRIPTION
    This template demonstrates how to create a reporting script that collects data,
    processes it, and outputs in multiple formats (CSV, HTML, JSON).

.PARAMETER ReportType
    The type of report to generate.

.PARAMETER OutputFormat
    The output format(s) for the report. Default is CSV.

.PARAMETER OutputPath
    The path where report files will be saved.

.PARAMETER SendEmail
    Send the report via email.

.PARAMETER EmailTo
    Email address(es) to send the report to.

.EXAMPLE
    .\Reporting-Script-Template.ps1 -ReportType "Users" -OutputFormat CSV,HTML

    Generates a user report in both CSV and HTML formats.

.EXAMPLE
    .\Reporting-Script-Template.ps1 -ReportType "Users" -SendEmail -EmailTo "admin@domain.com"

    Generates a report and emails it to the specified address.

.NOTES
    Author:         Your Name
    Created:        YYYY-MM-DD
    Version:        1.0
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('Users', 'Groups', 'Computers', 'Security')]
    [string]$ReportType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('CSV', 'HTML', 'JSON', 'Excel')]
    [string[]]$OutputFormat = @('CSV'),

    [Parameter(Mandatory = $false)]
    [ValidateScript({
        if (Test-Path $_ -PathType Container) { $true }
        else { throw "Output path does not exist: $_" }
    })]
    [string]$OutputPath = "$PSScriptRoot\Reports",

    [Parameter(Mandatory = $false)]
    [switch]$SendEmail,

    [Parameter(Mandatory = $false)]
    [ValidatePattern('^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$')]
    [string[]]$EmailTo
)

#region Functions
function Get-ReportData {
    [CmdletBinding()]
    param(
        [string]$Type
    )

    Write-Verbose "Collecting data for $Type report"

    # Simulate data collection based on report type
    switch ($Type) {
        'Users' {
            # Example: Get-ADUser -Filter * -Properties * | Select-Object Name, SamAccountName, Enabled, LastLogonDate
            $data = @(
                [PSCustomObject]@{Name = "User1"; Email = "user1@domain.com"; Enabled = $true; LastLogon = (Get-Date).AddDays(-1) }
                [PSCustomObject]@{Name = "User2"; Email = "user2@domain.com"; Enabled = $true; LastLogon = (Get-Date).AddDays(-5) }
                [PSCustomObject]@{Name = "User3"; Email = "user3@domain.com"; Enabled = $false; LastLogon = (Get-Date).AddDays(-30) }
            )
        }
        'Groups' {
            # Example: Get-ADGroup -Filter * | Select-Object Name, GroupScope, Members
            $data = @(
                [PSCustomObject]@{Name = "Group1"; Type = "Security"; MemberCount = 15 }
                [PSCustomObject]@{Name = "Group2"; Type = "Distribution"; MemberCount = 8 }
            )
        }
        Default {
            $data = @()
        }
    }

    return $data
}

function Export-ReportToCSV {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object[]]$Data,
        [string]$FilePath
    )

    Write-Verbose "Exporting to CSV: $FilePath"
    $Data | Export-Csv -Path $FilePath -NoTypeInformation -Encoding UTF8
}

function Export-ReportToHTML {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object[]]$Data,
        [string]$FilePath,
        [string]$Title
    )

    Write-Verbose "Exporting to HTML: $FilePath"

    $html = @"
<!DOCTYPE html>
<html>
<head>
    <title>$Title</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        table { border-collapse: collapse; width: 100%; margin-top: 20px; }
        th { background-color: #4CAF50; color: white; padding: 12px; text-align: left; }
        td { border: 1px solid #ddd; padding: 8px; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .footer { margin-top: 20px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <h1>$Title</h1>
    <p>Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")</p>
    <p>Total Records: $($Data.Count)</p>
    $(ConvertTo-Html -InputObject $Data -Fragment)
    <div class="footer">
        <p>Generated by PowerShell Reporting Script</p>
    </div>
</body>
</html>
"@

    $html | Out-File -FilePath $FilePath -Encoding UTF8
}

function Export-ReportToJSON {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object[]]$Data,
        [string]$FilePath
    )

    Write-Verbose "Exporting to JSON: $FilePath"
    $Data | ConvertTo-Json -Depth 10 | Out-File -FilePath $FilePath -Encoding UTF8
}

function Send-ReportEmail {
    [CmdletBinding()]
    param(
        [string[]]$To,
        [string]$Subject,
        [string]$Body,
        [string[]]$Attachments
    )

    Write-Verbose "Sending email report to: $($To -join ', ')"

    $emailParams = @{
        To          = $To
        From        = "reports@domain.com"
        Subject     = $Subject
        Body        = $Body
        BodyAsHtml  = $true
        SmtpServer  = "smtp.domain.com"
        Attachments = $Attachments
    }

    # Send-MailMessage @emailParams
    Write-Warning "Email sending is configured but commented out. Update SMTP settings and uncomment."
}
#endregion

#region Main Script
try {
    # Create output directory if it doesn't exist
    if (-not (Test-Path $OutputPath)) {
        New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
    }

    # Generate timestamp for file names
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $reportName = "$ReportType-Report-$timestamp"

    # Collect data
    Write-Host "Collecting data for $ReportType report..." -ForegroundColor Cyan
    $reportData = Get-ReportData -Type $ReportType

    if ($reportData.Count -eq 0) {
        Write-Warning "No data found for report type: $ReportType"
        exit
    }

    Write-Host "Found $($reportData.Count) items to report" -ForegroundColor Green

    # Export in requested formats
    $exportedFiles = @()

    foreach ($format in $OutputFormat) {
        $fileName = "$reportName.$($format.ToLower())"
        $filePath = Join-Path $OutputPath $fileName

        Write-Host "Generating $format report..." -ForegroundColor Cyan

        switch ($format) {
            'CSV' {
                Export-ReportToCSV -Data $reportData -FilePath $filePath
            }
            'HTML' {
                Export-ReportToHTML -Data $reportData -FilePath $filePath -Title "$ReportType Report"
            }
            'JSON' {
                Export-ReportToJSON -Data $reportData -FilePath $filePath
            }
            'Excel' {
                Write-Warning "Excel export requires ImportExcel module. Install with: Install-Module ImportExcel"
                # $reportData | Export-Excel -Path $filePath -AutoSize -TableName $ReportType
            }
        }

        if (Test-Path $filePath) {
            $exportedFiles += $filePath
            Write-Host "Report saved: $filePath" -ForegroundColor Green
        }
    }

    # Send email if requested
    if ($SendEmail -and $EmailTo) {
        $emailSubject = "$ReportType Report - $(Get-Date -Format 'yyyy-MM-dd')"
        $emailBody = @"
<h2>$ReportType Report</h2>
<p>Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")</p>
<p>Total Records: $($reportData.Count)</p>
<p>Please see attached report file(s).</p>
"@

        Send-ReportEmail -To $EmailTo -Subject $emailSubject -Body $emailBody -Attachments $exportedFiles
    }

    Write-Host "`nReport generation completed successfully!" -ForegroundColor Green
    Write-Host "Files generated: $($exportedFiles.Count)" -ForegroundColor Cyan
}
catch {
    Write-Error "Error generating report: $_"
    Write-Error $_.Exception.Message
    exit 1
}
#endregion
